name: Feed to Mastodon
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Update and deploy to Pages"]
    types:
      - completed
jobs:
  rss-to-mastodon:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@v6
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())
      - name: Retrieve cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/mastofeedbot
          key: feed-cache-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: feed-cache-
      - name: GitHub
        uses: "joschi/mastofeedbot@v0.1.3"
        with:
          # This is the RSS feed you want to publish
          rss-feed: https://jnv.github.io/istwitterapifree.com/feed.xml
          # Template of status posted to Mastodon (Handlebars)
          template: "{{item.description}}"
          # Visibility of the posted status (public | unlisted | private | direct)
          status-visibility: public
          # Mark Mastodon status as sensitive content
          sensitive: false
          # This is your instance address
          api-endpoint: https://masto.ai
          # This is the secret you created earlier
          api-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          # This is a path to the cache file, using the above cache path
          cache-file: ${{ github.workspace }}/mastofeedbot/cache.json
